theme = "gruvbox_dark_soft"

[editor]
mouse = false
bufferline = "multiple"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.inline-diagnostics]
cursor-line = "error"

[keys.normal]
"C-g" = [":write-all", ":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[editor.statusline]
right = [
    # "file-encoding",
    "file-type",
    # "file-line-ending",
    "separator",
    "file-name",
    # "read-only-indicator",
    "separator",
    "spacer",
    "version-control",
    "spacer",
    "separator",
    "file-modification-indicator",
]
left = [
    "mode",
    "selections",
    "primary-selection-length",
    "separator",
    "position",
    "position-percentage",
]

[editor.statusline.mode]
insert = "INSERT"
normal = "NORMAL"
select = "SELECT"
