local map = vim.keymap.set

map({ "n", "x" }, "<C-a>", function()
  require("opencode").ask("@this: ", { submit = true })
end, { desc = "Ask opencode" })
map({ "n", "x" }, "<C-x>", function()
  require("opencode").select()
end, { desc = "opencode actions" })
map({ "n", "x" }, "ga", function()
  require("opencode").prompt("@this")
end, { desc = "Add to opencode" })
map({ "n", "t" }, "<C-.>", function()
  require("opencode").toggle()
end, { desc = "Toggle opencode" })
map("n", "<S-C-u>", function()
  require("opencode").command("session.half.page.up")
end, { desc = "opencode ½ page up" })
map("n", "<S-C-d>", function()
  require("opencode").command("session.half.page.down")
end, { desc = "opencode ½ page down" })

map("n", "<Leader>rg", function()
  require("ror.commands").list_commands()
end, { desc = "RoR Commands" })
map("n", "<Leader>rq", function()
  require("ror.schema").list_table_columns()
end, { desc = "RoR Table Schema" })
map("n", "<Leader>rr", function()
  require("ror.schema").list_routes()
end, { desc = "RoR List Routes" })
map("n", "<Leader>ry", function()
  require("ror.schema").sync_routes()
end, { desc = "RoR Sync Routes" })

map({ "n", "x" }, "<leader>oa", function()
  require("opencode").ask("@this: ", { submit = true })
end, { desc = "Ask opencode" })

map({ "n", "x" }, "<leader>ox", function()
  require("opencode").select()
end, { desc = "opencode actions" })

map({ "n", "x" }, "<leader>og", function()
  require("opencode").prompt("@this")
end, { desc = "Add to opencode" })

map({ "n", "t" }, "<leader>ot", function()
  require("opencode").toggle()
end, { desc = "Toggle terminal" })
